{% set name = "qulacs" %}
{% set version = "0.1.10.1" %}
{% set sha256 = "7c3909ae63d352ed4b1481d63093cb5971c120c7577353e591a323b7a3d41ada" %}

package:
  # must not match any outputs for requirements to be handled correctly
  name: qulacs-conda
  version: {{ version }}

source:
  - url: https://github.com/qulacs/qulacs/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  # temporarily disable PyPy build (conda-forge/cupy-feedstock#43)
  skip: true  # [python_impl == "pypy"]
  skip: true  # [cuda_compiler_version in (undefined, "None")]
  skip: true  # [not linux]

#requirements:
#  #build:
#  #  - {{ compiler("c") }}
#  #  - {{ compiler("cxx") }}
#  #  - {{ compiler("cuda") }}
#  host:
#    - python
#    - pip
#    - setuptools

outputs:
  # this is the metapackage to ensure mutual exclusiveness
  - name: {{ name|lower }}
    version: {{ version }}
    build:
      number: 0
      string: {{ arch }}
    test:
      commands:
        - echo "qulacs metapackage is built"

  - name: {{ name|lower }}-gpu  # [cuda_compiler_version not in (undefined, "None")]
    version: {{ version }}
    build:
      script:
        # GCC and GXX are defined by conda-build
        - export C_COMPILER="${GCC}"
        - export CXX_COMPILER="${GXX}"
        - export CUDA_BIN_PATH=/usr/local/cuda/  # bad interaction between cmake and cuda on CF?
        - python setup_gpu.py install -vv
      missing_dso_whitelist:
        - '*/libcuda.*'
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - cmake
        - make  # [not win]
        - setuptools
      host:
        - python
        - pip
      run:
        - python
        - numpy
        - qulacs {{ version }} gpu
    test:
      imports:
        - qulacs
      source_files:
        - python/test/test_qulacs.py
      commands:
        - nvidia-smi
        - python test_qulacs.py

#  requires:
#    - pytest
#    - mock
#    - {{ compiler("c") }}
#    - {{ compiler("cxx") }}
#    - {{ compiler("cuda") }}  # tests need nvcc
#    #- scipy >=1.0,<1.1  <-- cause error
#
#  source_files:
#    - tests
#
#  #commands:
#  #  # ugly hack to see the linkage
#  #  - ldd ${STDLIB_DIR}/site-packages/cupy/cuda/cutensor.cpython-${CONDA_PY}m-x86_64-linux-gnu.so  # [cuda_compiler_version in ('10.1', '10.2')]

about:
  home: https://github.com/qulacs/qulacs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Qulacs is a Variational Quantum Circuit Simulator for Quantum Computation Research.

extra:
  recipe-maintainers:
    - leofang
