{% set name = "qulacs" %}
{% set version = "0.1.10.1" %}
{% set sha256 = "7c3909ae63d352ed4b1481d63093cb5971c120c7577353e591a323b7a3d41ada" %}

package:
  name: {{ name|lower }}-conda
  version: {{ version }}

source:
  - url: https://github.com/qulacs/qulacs/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  # temporarily disable PyPy build (conda-forge/cupy-feedstock#43)
  skip: true  # [python_impl == "pypy"]
  skip: true  # [cuda_compiler_version in (undefined, "None")]
  skip: true  # [not linux]

outputs:
  # the name "qulacs-conda" is reserved as a metapackage to ensure mutual exclusiveness
  - name: {{ name|lower }}-conda
    version: {{ version }}
    build:
      number: 0
      string: {{ arch }}
    test:
      commands:
        - echo "qulacs-conda metapackage is built"

  - name: {{ name|lower }}-gpu  # [cuda_compiler_version not in (undefined, "None")]
    version: {{ version }}
    build:
      script:
        # GCC and GXX are defined by conda-build
        - export C_COMPILER="${GCC}"
        - export CXX_COMPILER="${GXX}"
        - export CUDA_BIN_PATH=/usr/local/cuda/  # bad interaction between cmake and cuda on CF?
        - $PREFIX/bin/python setup_gpu.py install -vv  # "PYTHON" is undefined at this point
      missing_dso_whitelist:
        - '*/libcuda.*'
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - cmake
      host:
        - python
        - pip
        - setuptools
      run:
        - python
        - numpy
        - qulacs-conda {{ version }} gpu_{{ cuda_compiler_version }}
    test:
      imports:
        - qulacs
      requires:
        - scipy
      source_files:
        - python/test/test_qulacs.py
      commands:
        - nvidia-smi
        - python python/test/test_qulacs.py

about:
  home: https://github.com/qulacs/qulacs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Qulacs is a Variational Quantum Circuit Simulator for Quantum Computation Research.

extra:
  recipe-maintainers:
    - leofang
