{% set name = "qulacs" %}
{% set version = "0.1.10.1" %}
{% set sha256 = "7c3909ae63d352ed4b1481d63093cb5971c120c7577353e591a323b7a3d41ada" %}
{% set build = 0 %}

{% if cuda_compiler_version not in (undefined, "None") %}
{% set arch = "gpu" %}
{% set build_string = arch + cuda_compiler_version %}
{% else %}
{% set arch = "cpu" %}
{% set build_string = arch %}
{% endif %}

package:
  name: {{ name|lower }}-conda
  version: {{ version }}

source:
  - url: https://github.com/qulacs/qulacs/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  skip: true  # [python_impl == "pypy" or not linux]

outputs:
  # this is a metapackage to ensure mutual exclusiveness
  - name: qulacs-mutex
    version: {{ version }}
    build:
      number: 0
      string: {{ build_string }}
      run_exports:
        - {{ pin_subpackage('qulacs-mutex', exact=True) }}
    requirements: {}
    test:
      commands:
        - echo "qulacs-mutex metapackage is built"

  - name: {{ name|lower }}-gpu  # [arch == "gpu"]
    version: {{ version }}
    build:
      number: {{ build }}
      script:
        # GCC and GXX are defined by conda-build
        - export C_COMPILER="${GCC}"
        - export CXX_COMPILER="${GXX}"
        - export CUDA_BIN_PATH=/usr/local/cuda/  # bad interaction between cmake and cuda on CF?
        - $PREFIX/bin/python setup_gpu.py install -vv  # "PYTHON" is undefined at this point
      missing_dso_whitelist:
        - '*/libcuda.*'
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - cmake
      host:
        - python
        - pip
        - setuptools
      run:
        - python
        - numpy
        - qulacs-mutex {{ version }} {{ build_string }}
    test:
      imports:
        - qulacs
      requires:
        - scipy
      source_files:
        - python/test/test_qulacs.py
      commands:
        - nvidia-smi
        - python python/test/test_qulacs.py

  - name: {{ name|lower }}  # [arch == "cpu"]
    version: {{ version }}
    build:
      number: {{ build }}
      script:
        # GCC and GXX are defined by conda-build
        - export C_COMPILER="${GCC}"
        - export CXX_COMPILER="${GXX}"
        - $PREFIX/bin/python setup.py install -vv  # "PYTHON" is undefined at this point
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
      host:
        - python
        - pip
        - setuptools
      run:
        - python
        - numpy
        - qulacs-mutex {{ version }} {{ build_string }}
    test:
      imports:
        - qulacs

about:
  home: https://github.com/qulacs/qulacs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Qulacs is a Variational Quantum Circuit Simulator for Quantum Computation Research.

extra:
  recipe-maintainers:
    - leofang
